# Generated by Django 6.1.2 on 2026-10-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='未設定', max_length=100, verbose_name='教員名'),
            preserve_default=False,
        ),
    ]
